// Danh sách khách mời — Ty Ni 26th Birthday
// URL format: index.html?g=1
window.GUESTS = {
  "default": { name: "Quý khách",           title: "Kính mời", message: "Rất mong được gặp gặp bạn trong đêm tiệc đặc biệt này ✨" },
  "1":  { name: "A Cường +",            title: "Kính mời", message: "Rất hân hạnh được mời anh đến chung vui ✨" },
  "2":  { name: "Vc a Huy C Thảo",     title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "3":  { name: "Bé Lủng +",            title: "Kính mời", message: "Rất hân hạnh được mời bạn đến chung vui ✨" },
  "4":  { name: "A Nhân +",             title: "Kính mời", message: "Rất hân hạnh được mời anh đến chung vui ✨" },
  "5":  { name: "Trúc Nguyễn +",        title: "Kính mời", message: "Rất hân hạnh được mời bạn đến chung vui ✨" },
  "6":  { name: "Vc a Hải c Yến",       title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "7":  { name: "C Nữ +",               title: "Kính mời", message: "Rất hân hạnh được mời chị đến chung vui ✨" },
  "8":  { name: "C Huyền +",            title: "Kính mời", message: "Rất hân hạnh được mời chị đến chung vui ✨" },
  "9":  { name: "C Hoàng Vy +",         title: "Kính mời", message: "Rất hân hạnh được mời chị đến chung vui ✨" },
  "10": { name: "A Khanh",              title: "Kính mời", message: "Rất hân hạnh được mời anh đến chung vui ✨" },
  "11": { name: "Vc c Trang",           title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "12": { name: "Vc c Nga a Phúc",      title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "13": { name: "Em Ni +",              title: "Kính mời", message: "Rất hân hạnh được mời em đến chung vui ✨" },
  "14": { name: "Em Hiếu +",            title: "Kính mời", message: "Rất hân hạnh được mời em đến chung vui ✨" },
  "15": { name: "Vc c Trinh",           title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "16": { name: "C Ngọc Singer +",      title: "Kính mời", message: "Rất hân hạnh được mời chị đến chung vui ✨" },
  "17": { name: "C Khánh +",            title: "Kính mời", message: "Rất hân hạnh được mời chị đến chung vui ✨" },
  "18": { name: "Vc c Nghĩa",           title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "19": { name: "Chị 3 +",              title: "Kính mời", message: "Rất hân hạnh được mời chị đến chung vui ✨" },
  "20": { name: "Vc a Thái Băm",        title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "21": { name: "Vc a Tiến Black",      title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "22": { name: "Vc Thương Tây",        title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "23": { name: "Vc a Quí",             title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "24": { name: "Chị Bi +",             title: "Kính mời", message: "Rất hân hạnh được mời chị đến chung vui ✨" },
  "25": { name: "Vc Ac Vương Giang",    title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "26": { name: "Chị Viên +",           title: "Kính mời", message: "Rất hân hạnh được mời chị đến chung vui ✨" },
  "27": { name: "Vc chị Phương",        title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "28": { name: "C Phương phạm +",      title: "Kính mời", message: "Rất hân hạnh được mời chị đến chung vui ✨" },
  "29": { name: "Vc c Sinh",            title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "30": { name: "Bé My +",              title: "Kính mời", message: "Rất hân hạnh được mời bạn đến chung vui ✨" },
  "31": { name: "Vc bé Hoàng Loan",     title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
  "32": { name: "Hồng Hí +",            title: "Kính mời", message: "Rất hân hạnh được mời bạn đến chung vui ✨" },
  "33": { name: "Mun Nail +",           title: "Kính mời", message: "Rất hân hạnh được mời bạn đến chung vui ✨" },
  "34": { name: "Vc a Lâm c Thương",    title: "Kính mời", message: "Rất hân hạnh được mời anh chị đến chung vui ✨" },
};
