const WEDDING_DATA = {
    couple: {
        groom: 'Nguyễn Trọng Nghĩa',
        bride: 'Ngô Thu Thuỷ',
        shortName: 'N & T',
    },

    groomFamily: {
        father: 'Nguyễn Trọng Hưng',
        mother: 'Lê Thị Kim Dung',
    },

    brideFamily: {
        father: 'Ngô Ngọc Sơn',
        mother: 'Nguyễn Thị Thu Hồng',
    },

    ceremony: {
        title: 'Lễ Thành Hôn',
        date: '29-03-2026',
        day: 'Chủ Nhật',
        time: '11:00',
        lunar: '11 tháng 02 năm Bính Ngọ',
        venue: 'Hội trường Hoa Ban',
        address: 'Trung tâm Xúc tiến Đầu tư Thương mại & Du lịch tỉnh Điện Biên',
        note: 'Cạnh hầm Đờ Cát',
        location: 'Điện Biên',
    },

    reception: {
        title: 'Báo Hỷ',
        date: '03-04-2026',
        day: 'Thứ Sáu',
        time: '18:30',
        lunar: '16 tháng 02 năm Bính Ngọ',
        venue: 'Nhà hàng Trống Đồng Palace Mễ Trì',
        room: 'Phòng Lotus 3 - Tầng 2',
        address: '52 Miếu Đàm - Mễ Trì - Hà Nội',
        location: 'Hà Nội',
    },

    guests: [
        { id: 1, name: 'Chị Hương cùng người thương' },
        { id: 2, name: 'Chị Thiên Phương cùng anh nhà' },
        { id: 3, name: 'Chị Ánh cùng người thương' },
        { id: 4, name: 'Chị Tú Anh cùng người thương' },
        { id: 5, name: 'Chị Oanh cùng anh nhà' },
        { id: 6, name: 'Bạn Quỳnh cùng anh nhà' },
        { id: 7, name: 'Bạn Sinh cùng người thương' },
        { id: 8, name: 'Bạn Ánh cùng người thương' },
        { id: 9, name: 'Bạn Khánh Huyền cùng người thương' },
        { id: 10, name: 'Bạn Giang cùng người thương' },
        { id: 11, name: 'Bạn Kim Ngân cùng người thương' },
        { id: 12, name: 'Bạn Ngọc Mai cùng người thương' },
        { id: 13, name: 'Bạn Thảo cùng người thương' },
        { id: 14, name: 'Anh Minh cùng người thương' },
        { id: 15, name: 'Bạn Hiếu cùng người thương' },
        { id: 16, name: 'Bạn Dương cùng người thương' },
        { id: 17, name: 'Anh Thành cùng vợ' },
        { id: 18, name: 'Chị Term Term cùng người thương' },
        { id: 19, name: 'Chị Jin Ju cùng người thương' },
        { id: 20, name: 'Bạn Lizh cùng bạn Ngọc' },
        { id: 21, name: 'Bạn Mỡ yêu cùng anh nhà' },
        { id: 22, name: 'Bạn Bi Béo cùng gia đình' },
        { id: 23, name: 'Bạn Thư Thư cùng gia đình' },
        { id: 24, name: 'Bạn Thủy cùng người thương' },
        { id: 25, name: 'Ck Tuyến cùng người thương' },
        { id: 26, name: 'Bạn Linh cùng người thương' },
        { id: 27, name: 'Bạn Nguyệt cùng anh nhà' },
        { id: 28, name: 'Anh Chiến cùng vợ' },
        { id: 29, name: 'Anh Trường cùng người thương' },
        { id: 30, name: 'Chị Hoa cùng người thương' },
        { id: 31, name: 'Em Khánh Hạ cùng người thương' },
        { id: 32, name: 'Bạn Uyên cùng người thương' },
        { id: 33, name: 'Thảo iu cùng người thương' },
        { id: 34, name: 'Bạn Thảo cùng anh nhà' },
        { id: 35, name: 'Chị Linh cùng anh nhà' },
        { id: 36, name: 'Anh Thái cùng chị nhà' },
        { id: 37, name: 'Anh Nghĩa cùng gia đình' },
        { id: 38, name: 'Chị Mỹ cùng người thương' },
        { id: 39, name: 'Chị Hằng cùng gia đình' },
        { id: 40, name: 'Bạn Trang cùng người thương' },
        { id: 41, name: 'Bạn Nhung cùng người thương' },
        { id: 42, name: 'Chị Nga cùng gia đình' },
        { id: 43, name: 'Chị Mai Anh cùng gia đình' },
        { id: 44, name: 'Bạn Quyền Anh cùng gia đình' },
        { id: 45, name: 'Bạn Quỳnh Anh cùng người thương' },
        { id: 46, name: 'Chị Nghĩa cùng gia đình' },
        { id: 47, name: 'Em Hiền cùng người thương' },
    ],
};
