var GUEST_LIST = [
    { id: 1, name: "Bạn Nga" },
    { id: 2, name: "V/C Bạn Như" },
    { id: 3, name: "V/C Bạn Vân" },
    { id: 4, name: "V/C Bạn Tài" },
    { id: 5, name: "V/C Bạn Ly" },
    { id: 6, name: "V/C Bạn Phương Ni" },
    { id: 7, name: "V/C Nguyệt" },
    { id: 8, name: "V/C Minh Tâm" },
    { id: 9, name: "V/C Chị Hoài" },
    { id: 10, name: "V/C Bạn Châu" },
    { id: 11, name: "V/C Bạn Toàn" },
    { id: 12, name: "V/C Bạn Hưng" },
    { id: 13, name: "V/C Bạn Trân" },
    { id: 14, name: "V/C Bạn Trầm" },
    { id: 15, name: "V/C Bạn Ân" },
    { id: 16, name: "V/C Bạn Hiền" },
    { id: 17, name: "V/C Bạn Dương" },
    { id: 18, name: "V/C Bạn Lộc" },
    { id: 19, name: "V/C Bạn Phước" },
    { id: 20, name: "V/C Bạn Nhuận" },
    { id: 21, name: "V/C Bạn Khải" },
    { id: 22, name: "V/C Bạn Ngọc Huyền" },
    { id: 23, name: "Bạn Toàn +" },
    { id: 24, name: "Bạn Trang +" },
    { id: 25, name: "Bạn Quân +" },
    { id: 26, name: "V/C Bạn Sơn" },
    { id: 27, name: "Bạn Ngọc Thảo +" },
    { id: 28, name: "Bạn Phương +" },
    { id: 29, name: "Em Nhi +" },
    { id: 30, name: "Em Phấn +" },
    { id: 31, name: "Em Nhung +" },
    { id: 32, name: "Bạn Linh +" },
    { id: 33, name: "V/C Bạn Đạo" },
    { id: 34, name: "V/C Chị Trang" },
    { id: 35, name: "V/C Sơn" },
];
